{
    'name': "Real Estate",
    'summary': "This is the real estate",
    'description': """ Real Estate""",
    'category': 'Accounting/Accounting',
    'version': '19.0.0',
    'depends': ['base','web', 'mail'],
    'data': [
        'security/real_estate_security.xml',
        'security/ir.model.access.csv',
        'data/real_estate_sequence.xml',
        'views/real_estate_properties_views.xml',
        'views/real_estate_types_views.xml',
        'views/real_estate_tags_views.xml',
        'views/real_estate_offers_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': True,
    'author': 'Odoo KHS',
    'license': 'LGPL-3',
}
